package com.mindshield.app

// This is a placeholder for the generated R class
// The actual R class will be generated by the Android Gradle Plugin
// This is just to make the code compile
class R {
    class string {
        companion object {
            // Add any string resources here that you reference in code
            // They should match the ones in res/values/strings.xml
        }
    }
}
